#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo $pwd
function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'yarn.lock'; then
  echo "📦 yarn.lock changed. Run yarn to bring your dependencies up to date."
  yarn install --frozen-lockfile
fi
